name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - name: build
      run: |
        cd ${{ github.workspace }}
        dir
        make v=1
        make clean windows_delete_command=rm
    - uses: actions/upload-artifact@v2
      with:
        name: windows_build_static_metadata
        path: Primer++.exe

  build_macos:
    runs-on: macos-latest
    steps:
    - name: build
      run: |
        cd ${{ github.workspace }}
        ls
        make v=1
        ls obj
        make clean
    - uses: actions/upload-artifact@v2
      with:
       name: macos_build_dynamic
       path: Primer++

  build_linux:
    runs-on: ubuntu-latest
    steps:
    - name: build
      run: |
        cd ${{ github.workspace }}
        ls
        make v=1
        ls obj
        make clean
    - uses: actions/upload-artifact@v2
      with:
        name: linux_build_static
        path: Primer++
